apps/member/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = "member"
urlpatterns = [
    path('<int:pk>', MemberInfo.as_view(), name='member_info'),
]

findmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('api/', include('apps.api.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('apps.member.urls')),
    path('', include('apps.core.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/member/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
from django.db.models import Count
from django.conf import settings
from apps.core.models import BaseModel
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
import os

# Create your models here.


def mem_img_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ' '.join(arr)
    extension = filename.split('.')[-1]
    return 'member/profile/{}.{}'.format(pid, extension)


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=45, blank=True)
    short_desc = models.CharField(max_length=200, blank=True, null=True)
    options = models.CharField(max_length=200, blank=True, null=True)
    picture = ProcessedImageField(upload_to = mem_img_path,
                                processors=[ResizeToFit(width=150, upscale=False)],
                                format='JPEG',
                                options={'quality':90},
                                blank=True,
                                null=True,
                                )
    detail = RichTextUploadingField(config_name='default', blank=True, null=True)
    skills = TaggableManager(blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.picture.url
        except:
            url = ''
        return url
    
    @property
    def longitude(self):
        return self.point[0]

    @property
    def latitude(self):
        return self.point[1]

    # 유저 삭제 시 media 폴더 프로필 사진 삭제
    def delete(self, *args, **kwargs):
        if self.picture:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.picture.path))
        super(Profile, self).delete(*args, **kwargs)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        user_count = User.objects.count()
        print(user_count)
        Profile.objects.create(user=instance, name="Mate %s" %(user_count))


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class CVCategory(BaseModel):
    title = models.CharField(max_length=20)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    def __str__(self):
        return f"{self.title}"


POSITION = [
    ('1', '사원'),
    ('2', '주임'),
    ('3', '대리'),
    ('4', '과장'),
    ('5', '차장'),
    ('6', '부장'),
    ('7', '임원 이상'),
    ('8', '기타'),
]

EDU_SELECT = [
    ('1', '졸업'),
    ('2', '졸업예정'),
    ('3', '중퇴'),
    ('4', '휴학'),
    ('5', '재학'),
]

class CVItem(BaseModel):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    category = models.ForeignKey(CVCategory, on_delete=models.CASCADE, default=None)
    # Company
    company = models.CharField(max_length=100, blank=True, null=True)
    company_start_date = models.DateField(blank=True, null=True)
    company_end_date = models.DateField(blank=True, null=True)
    company_career = models.CharField(max_length=100, choices=POSITION, blank=True, null=True)
    # Education
    education = models.CharField(max_length=100, blank=True, null=True)
    education_status = models.CharField(max_length=100, choices=EDU_SELECT, blank=True, null=True)
    education_major = models.CharField(max_length=100, blank=True, null=True)
    # Projects
    projects = models.CharField(max_length=100, blank=True, null=True)
    projects_date = models.DateField(blank=True, null=True)
    projects_desc = models.TextField(blank=True, null=True)
    # Self intro
    intro = models.TextField(blank=True, null=True)
    # license
    license_list = models.CharField(max_length=100, blank=True, null=True)
    license_list_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.category} of {self.profile.name}"

apps/member/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic import DetailView
# Create your views here.

class MemberInfo(DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'member_info/member_info.html'

apps/member/templates/member_info/member_info.html
{% extends 'index.html' %}

{% block title %}
{% endblock %}

{% block style %}
<style>
    .profile_header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        width: 800px;
        margin: auto;
        padding: 1rem 0;
    }

    .member_name {
        font-size: 2rem;
    }

    .member_info span {
        font-size: .7rem;
        background-color: gray;
        color: white;
        border-radius: 4px;
        padding: .2rem .8rem;
    }

    .profile_contact {
        margin-top: 1rem;
    }

    .profile_contact>a {
        display: block;
        font-weight: 300;
        font-size: 1.2rem;
    }

    .profile_img {
        border-radius: 50%;
        border: 4px solid #efefef;
        width: 124px;
        height: 124px;
    }

    .profile_btns {
        margin-top: 1rem;
    }

    .profile_btns>a {
        font-size: 1rem;
        font-weight: 300;
        padding: .4rem .9rem;
        border-radius: 4px;
        color: white;
    }

    .profile_btns .profile_modify {
        background-color: green;
    }

    .profile_btns .profile_resign {
        background-color: #2b2b2b;
    }

    .cv_wrapper {
        width: 800px;
        margin: auto;
        min-height: 100vh;
    }

    .item_category {
        padding-top: 1rem;
        font-weight: 500;
        font-size: 1.5rem;
    }

    .item_box {
        margin-top: 1rem;
        background-color: white;
        border: 1px solid #efefef;
        padding: 1rem;
        font-weight: 300;
        display: flex;
        justify-content: space-between;
    }
</style>
{% endblock %}

{% block header_content %}
<div class="profile_header">
    <div class="member_info">
        <h2 class="member_name">{{profile.name}}</h2>
        {% for skill in profile.skills.all %}
        <span>#{{skill}}</span>
        {% endfor %}
        <div class="profile_contact">
            <a class="email">{{profile.user.email}}</a>
            <a class="phone">079-506-3972</a>
        </div>
        {% if profile.user == request.user %}
        <div class="profile_btns">
            <a class="profile_modify">프로필 수정</a>
            <a class="profile_resign">회원 탈퇴</a>
        </div>
        {%endif%}
    </div>
    <img class="profile_img" src="{{profile.picture.url}}">
</div>
{% endblock %}


{% block content %}

<div class="cv_wrapper">
    <h4 class="item_category">Company</h4>
    {% for item in profile.cvitem_set.all %}
    {% if item.category.id == 1 %}
    <div class="item_box {{item.category.slug}}" data-category={{item.category}}>
        <span>{{item.company}}</span>
        <span>{{item.get_company_career_display}}</span>
        <span>{{item.company_start_date}} ~ {{item.company_end_date}}</span>
    </div>
    {% elif item.category.id == 2 %}
    <div class="item_box {{item.category.slug}}" data-category={{item.category}}>
        <span>{{item.education}}</span>
        <span>{{item.get_education_status_display}}</span>
        <span>{{item.education_major}}</span>
    </div>

    {% endif %}
    {% endfor %}

    <script>
        var title = document.createElement('h4');
        title.setAttribute('class', 'item_category')
        let cv_list = document.querySelector('.cv_wrapper');
        let item_box = document.querySelectorAll('.item_box');
        for (i = 0; i < item_box.length; i++) {
            console.log(item_box[i])
            if (item_box[i].dataset.category != item_box[i + 1].dataset.category) {
                title.innerHTML = `${item_box[i + 1].dataset.category}`;
                cv_list.insertBefore(title, item_box[i + 1]);
            }
        }
    </script>


    {% endblock %}