apps/core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = "core"

urlpatterns = [
    # 팀 관련
    path('team_delete/<str:team_pk>/', team_delete, name="team_delete"),
    path('team_management/<str:team_pk>/', team_management, name="team_management"),
    path('team_register_reqeust/<str:team_pk>/', team_register_reqeust, name="team_register_reqeust"),
    path('team_detail/<str:team_pk>/', team_detail, name="team_detail"),
    path('update_team/<str:team_pk>/', update_team, name="update_team"),
    path('make_team/', make_team, name="make_team"),
    path('team_select/', team_select, name="team_select"),
    # 멤버 관련
    path('update_recruit/<str:recruit_pk>/', update_recruit, name="update_recruit"),
    path('team_recruit/<str:team_pk>/', team_recruit, name="team_recruit"),
    path('members/', member_list, name="member_list"),
    path('', main_page, name="main_page"),
]

findmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('api/', include('apps.api.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('apps.member.urls')),
    path('', include('apps.core.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

apps/teams/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit, ResizeToFill
from django.db.models import Count
from django.conf import settings
from apps.core.models import BaseModel
from apps.member.models import Profile
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
import os
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


def team_img_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ' '.join(arr)
    extension = filename.split('.')[-1]
    return 'team/{}.{}'.format(pid, extension)

PURPOSE_CHOICE = [
    ('1', '창업'),
    ('2', '취미'),
    ('3', '사이드프로젝트'),
    ('4', '스터디'),
    ('5', 'ETC'),
]

class Team(BaseModel):
    name = models.CharField(max_length=20)
    short_description = models.TextField(max_length=1024)
    purpose = models.CharField(max_length=1, choices=PURPOSE_CHOICE, null=True, blank=True)
    logo = ProcessedImageField(upload_to = team_img_path,
                                   processors = [ResizeToFill(
                                       width=200, height=200, upscale=True)],
                                   format='JPEG',
                                   options={'quality':90},
                                   blank=True,
                                   null=True)
    team_banner = ProcessedImageField(upload_to = team_img_path,
                                   processors = [ResizeToFill(
                                       width=1280, height=480, upscale=True)],
                                   format='JPEG',
                                   options={'quality':90},
                                   blank=True,
                                   null=True)
    team_detail = RichTextUploadingField(config_name='default', blank=True, null=True)

    def __str__(self):
        return '%s' % self.name

    def delete(self, *args, **kwargs):
        if self.logo or self.team_banner:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.logo.path))
            os.remove(os.path.join(settings.MEDIA_ROOT, self.team_banner.path))
        super(Team, self).delete(*args, **kwargs)


class TeamOrg(MPTTModel):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, related_name='team_org')
    parent = TreeForeignKey('self', verbose_name='parent', related_name='children', on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
    position = models.CharField(verbose_name='직책', max_length=30, default="팀장")
    authority = models.BooleanField(default=False)

    class Meta:
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['parent']

    @property
    def title(self):
        return self.team.name
    @property
    def is_leader(self):
        if self.level == 0:
            return True
        else:
            return False
CAREER_LEVEL = [
    ('1','경력 무관'),
    ('2','2년 미만'),
    ('3','5년 미만'),
    ('4','10년 미만'),
    ('5','10년 이상'),
]

class FindMember(BaseModel):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='find_member')
    title = models.CharField(max_length=200)
    essencial = models.CharField(max_length=200)
    plus = models.CharField(max_length=100)
    msg = RichTextUploadingField(config_name='default', blank=True, null=True)
    manpower = models.IntegerField()
    career = models.CharField(max_length=1, choices=CAREER_LEVEL)
    contact_name = models.CharField(max_length=100)
    contact_phone = models.CharField(max_length=100)
    contact_email = models.EmailField(max_length=254)

    def __str__(self):
        return f"{self.title} of {self.team.name}"


REG_STATUS = [
    ('1', 'REGISTERED'),
    ('2', 'APPROVE'),
    ('3', 'REJECT'),
]


class RegisteredMember(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    notice = models.ForeignKey(FindMember, on_delete=models.CASCADE, related_name='registered_user', null=True, blank=True)
    status = models.CharField(max_length=1, choices=REG_STATUS, null=True)
    msg = RichTextUploadingField(config_name='default', blank=True, null=True)

    def __str__(self):
        return f"{self.user} request for {self.team.name}"

apps/teams/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from ckeditor.widgets import CKEditorWidget

CHOICES = [
    ('1', '창업'),
    ('2', '취미'),
    ('3', '사이드프로젝트'),
    ('4', '스터디'),
    ('5', 'ETC'),
]

class TeamRegisterForm(forms.ModelForm):
    name = forms.CharField(label='팀 이름', widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '팀 이름을 알려주세요 (최대 20자)'
    }))
    short_description = forms.CharField(label='팀 소개', widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '간략한 팀 소개를 작성해주세요 (최대 50자)'
    }))
    purpose = forms.CharField(widget=forms.Select(choices=CHOICES, attrs={
        'required':'required'
    }))
    logo = forms.FileField(label='팀 로고', widget=forms.FileInput(attrs={
        'class':'hidden',
        'required':'required'
    }))
    team_banner = forms.FileField(label='팀 배너', widget=forms.FileInput(attrs={
        'class':'hidden',
        'required':'required'
    }))
    class Meta:
        model = Team
        field = '__all__'
        exclude = ()


CAREERS = [
    ('1','경력 무관'),
    ('2','2년 미만'),
    ('3','5년 미만'),
    ('4','10년 미만'),
    ('5','10년 이상'),
]


class TeamRecruitForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집공고 제목을 입력해주세요.'
    }))
    essencial = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '지원자격을 입력해주세요.'
    }))
    plus = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '우대사항을 입력해주세요.'
    }))
    manpower = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 인원 수를 입력해주세요.'
    }))
    career = forms.CharField(widget=forms.Select(choices=CAREERS, attrs={
        'required':'required'
    }))
    contact_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 담당자 이름을 입력해주세요.'
    }))
    contact_phone = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 담당자 전화번호를 입력해주세요.'
    }))
    contact_email = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 담당자 이메일주소를 입력해주세요.'
    }))
    msg = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = FindMember
        field = '__all__'
        exclude = ('team',)


class RegisterRequestForm(forms.ModelForm):

    class Meta:
        model = RegisteredMember
        field = '__all__'
        exclude = ('user','team','status',)

apps/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from apps.teams.models import *
from apps.member.models import *
from apps.teams.forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from ckeditor.fields import RichTextField
from django.urls import reverse
# Create your views here.

def main_page(request):
    teams = Team.objects.all()
    context = {
        'teams':teams,
    }
    return render(request, 'findteam/teams.html', context)


def member_list(request):
    members = Profile.objects.all()
    context = {
        'members':members,
    }
    return render(request, 'findmate/members.html', context)


@login_required
def make_team(request):
    posting_type = "create"
    if request.method == 'POST':
        form = TeamRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            newTeam = form.save(commit=False)
            newTeam.save()
            print(newTeam)
            team_org = TeamOrg.objects.create(user=request.user, team=newTeam)
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = TeamRegisterForm()
    context = {
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findteam/maketeam.html', context)

@login_required
def update_team(request, team_pk):
    posting_type = "update"
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        print('업데이트 시작')
        form = TeamRegisterForm(request.POST, request.FILES, instance=team)
        print(form)
        if form.is_valid():
            print('The form is valid')
            newTeam = form.save(commit=False)
            newTeam.save()
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = TeamRegisterForm(instance=team)
    context = {
        'team':team,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findteam/maketeam.html', context)

@login_required
def team_select(request):
    teams = Team.objects.filter(team_org__user=request.user, team_org__level=0)
    context = {
        'teams':teams,
    }
    return render(request, 'findmate/select_team.html', context)

@login_required
def team_recruit(request, team_pk):
    posting_type = "create"
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        form = TeamRecruitForm(request.POST, request.FILES)
        if form.is_valid():
            newRecruit = form.save(commit=False)
            newRecruit.team = team
            newRecruit.save()
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = TeamRecruitForm()
    context = {
        'team':team,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findmate/recruit.html', context)

@login_required
def update_recruit(request, recruit_pk):
    posting_type = "update"
    recruit = get_object_or_404(FindMember, pk=recruit_pk)
    team = recruit.team
    if request.method == 'POST':
        form = TeamRecruitForm(request.POST, request.FILES, instance=recruit)
        if form.is_valid():
            newRecruit = form.save(commit=False)
            newRecruit.team = team
            newRecruit.save()
            form.save_m2m()

            return redirect(reverse('core:team_management', kwargs={"team_pk": team.pk}))
    else:
        form = TeamRecruitForm(instance=recruit)
    context = {
        'team':team,
        'recruit':recruit,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findmate/recruit.html', context)


# 팀 디테일 페이지
@login_required
def team_detail(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    team_org = TeamOrg.objects.filter(team=team)
    try:
        if team_org.get(Q(user=request.user)&(Q(position="팀장")|Q(position="부팀장"))):
            authority = True
    except:
        authority = False        
    context = {
        'team':team,
        'team_org':team_org,
        'authority':authority,
    }
    return render(request, 'findteam/team_detail.html', context)


# 팀 가입 신청 페이지
@login_required
def team_register_reqeust(request, team_pk):
    posting_type = "create"
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        form = RegisterRequestForm(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            newRequest = form.save(commit=False)
            newRequest.team = team
            newRequest.user = request.user
            newRequest.status = '1'
            newRequest.save()
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = RegisterRequestForm()
    context = {
        'team':team,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findteam/team_register.html', context)


# 팀관리 페이지
@login_required
def team_management(request, team_pk):
    # 팀 관리페이지 첫 로딩에 필요한 팀 정보
    team = get_object_or_404(Team, pk=team_pk)

    # 팀 기본정보 관리에 필요한 코드
    team_base_form = TeamRegisterForm(instance=team)

    # 팀 조직도 정보
    team_org = TeamOrg.objects.filter(team=team)

    # 팀 모집공고용 ckeditor
    recruit_update_form = TeamRecruitForm()

    context = {
        'team':team,
        'team_base_form':team_base_form,
        'team_org':team_org,
        'recruit_update_form':recruit_update_form,
    }
    return render(request, 'findteam/team_management.html', context)


@login_required
def team_delete(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    team.delete()
    return redirect('/')

apps/core/templates/findteam/team_management/org_management.html
<!-- 조직도 관리 -->
<style>
    .team_mgmt_content ul {
        display: flex;
        justify-content: space-around;
        margin-bottom: 20px;
    }

    .team_mgmt_content ul li,
    .member_info {
        text-align: center;
        width: 200px;
    }

    .member_info {
        padding: 12px 20px;
        font-size: 16px;
        border-radius: 10px;
        outline: none;
        border: none;
        border-bottom: 1px solid #efefef;
    }

    .member_info.check {
        vertical-align: middle;
    }

    .team_mgmt_form {
        position: relative;
    }

    .modifyBtnWrap {
        display: flex;
        width: 100%;
        justify-content: flex-end;
    }

    .modify_member {
        background-color: #0099cc;
        border: none;
        width: 200px;
        text-align: center;
    }
</style>
<div class="team_mgmt_content" data-group="org">
    <ul>
        <li>직책</li>
        <li>팀원명</li>
        <li>권한부여</li>
    </ul>
    <form class="team_mgmt_form" action="">

        {% load mptt_tags %}
        {% recursetree team_org %}
        <ul>
            <li>
                <input class="member_info" type="text" value="{{node.position}}">
            </li>
            <li>
                <input class="member_info" type="text" value="{{node.user.profile.name}}">
            </li>
            <li>
                <input class="member_info check" type="checkbox">
            </li>
        </ul>
        {% if not node.is_leaf_node %}
        {{children}}
        {% endif %}
        {% endrecursetree %}
        <div class="modifyBtnWrap">
            <input type="sumit" value="저장" class="btn modify_member">
        </div>
    </form>
</div>

apps/core/templates/findteam/team_management/recruit_management.html
<style>
    .team_recruit_btn_list span {
        cursor: pointer;
    }
    .tab_content {
        width: 100%;
    }
</style>
<!-- 모집공고 관리 -->
<div class="team_mgmt_content" data-group="recruit">
    <form method="POST" action="{% url 'core:update_team' team.pk %}" enctype="multipart/form-data" novalidate>
        <div class="form_header">
            <div class="header_text">
                <h3>모집공고를 선택해주세요.</h3>
                <span>모집공고를 생성하거나 수정하고 지원자를 확인하여 팀원에 추가합니다</span>
                <div class="team_recruit_wrapper">
                    {% for recruit in team.find_member.all %}
                    <div class="team_recruit_item">
                        <h4 class="team_recruit_title">{{recruit.title}}</h4>
                        <span>{{recruit.get_career_display}} {{recruit.manpower}}명 /
                            {{recruit.registered_user.all.count}}명 지원</span>
                        <div class="team_recruit_btn_list">
                            <a href="{% url 'core:update_recruit' recruit.pk %}" class="team_recruit_modify recruit_btn" data-recruit="{{recruit.pk}}" data-popup="popup_recruit">공고수정</a>
                            <span class="team_recruit_applicants popup_btn recruit_btn" data-recruit="{{recruit.pk}}" data-popup="popup_applicant">지원확인</span>
                            <span class="team_recruit_delete recruit_btn">공고삭제</span>
                        </div>
                    </div>
                    {% endfor %}
                    <a class="team_recruit_item" href="{% url 'core:team_recruit' team.pk %}">
                        <h1 class="team_recruit_create">+</h1>
                        <h4 class="team_recruit_title">새로운 공고 만들기</h4>
                        <span>새로운 모집공고를 생성합니다</span>
                    </a>
                </div>

            </div>
        </div>
    </form>
</div>


<div class="popup_wrapper popup_applicant hidden">
    <div class="popup_bg"></div>
    <div class="popup_window">
        지원자 페이지입니다.
    </div>
</div>

<script>



</script>

apps/core/templates/findteam/team_management/team_info.html
<div class="team_mgmt_content active" data-group="basic_info">
    <form method="POST" action="{% url 'core:update_team' team.pk %}" enctype="multipart/form-data" novalidate>
        <div class="form_header">
            <div class="header_text">
                <h3>{{team.name}} 팀 정보 수정</h3>
                <span>팀의 기본정보를 수정합니다.</span>
            </div>
            <input type="submit" class="btn register_team" value="수정하기">
        </div>
        <div class="form_content">
            {% csrf_token %}
            <div class="form_control">
                <label class="form_label" for="team_name">팀 이름</label>
                {{team_base_form.name}}
            </div>
            <div class="form_control">
                <label class="form_label" for="team_desc">팀 소개</label>
                {{team_base_form.short_description}}
            </div>
            <div class="form_control">
                <label class="form_label" for="id_purpose">팀 목표</label>
                {{team_base_form.purpose}}
            </div>
            <div class="form_control">
                <span class="form_label">팀 로고</span>
                <label class="upload_label" for="id_logo">업로드 (200x200)</label>
                {{team_base_form.logo}}
            </div>
            <div class="form_control">
                <span class="form_label">팀 배너</span>
                <label class="upload_label" for="id_team_banner">업로드 (1280x480)</label>
                {{team_base_form.team_banner}}
            </div>
            <div class="form_control">
                <h4 class="form_label" class="form_label">팀 소개</h4>
                {{team_base_form.team_detail|safe}}
            </div>

        </div>
    </form>
</div>