apps/core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = "core"

urlpatterns = [
    # 팀 관련
    path('team_delete/<str:team_pk>/', team_delete, name="team_delete"),
    path('team_management/<str:team_pk>/', team_management, name="team_management"),
    path('team_register_reqeust/<str:team_pk>/', team_register_reqeust, name="team_register_reqeust"),
    path('team_detail/<str:team_pk>/', team_detail, name="team_detail"),
    path('update_team/<str:team_pk>/', update_team, name="update_team"),
    path('make_team/', make_team, name="make_team"),
    path('team_select/', team_select, name="team_select"),
    # 멤버 관련
    path('update_recruit/<str:recruit_pk>/', update_recruit, name="update_recruit"),
    path('team_recruit/<str:team_pk>/', team_recruit, name="team_recruit"),
    path('members/', member_list, name="member_list"),
    path('', main_page, name="main_page"),
]

apps/member/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = "member"
urlpatterns = [
    path('<int:pk>', MemberInfo.as_view(), name='member_info'),
]

findmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('api/', include('apps.api.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('apps.member.urls')),
    path('', include('apps.core.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

apps/teams/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit, ResizeToFill
from django.db.models import Count
from django.conf import settings
from apps.core.models import BaseModel
from apps.member.models import Profile
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
import os
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


def team_img_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ' '.join(arr)
    extension = filename.split('.')[-1]
    return 'team/{}.{}'.format(pid, extension)

PURPOSE_CHOICE = [
    ('1', '창업'),
    ('2', '취미'),
    ('3', '사이드프로젝트'),
    ('4', '스터디'),
    ('5', 'ETC'),
]

class Team(BaseModel):
    name = models.CharField(max_length=20)
    short_description = models.TextField(max_length=1024)
    purpose = models.CharField(max_length=1, choices=PURPOSE_CHOICE, null=True, blank=True)
    logo = ProcessedImageField(upload_to = team_img_path,
                                   processors = [ResizeToFill(
                                       width=200, height=200, upscale=True)],
                                   format='JPEG',
                                   options={'quality':90},
                                   blank=True,
                                   null=True)
    team_banner = ProcessedImageField(upload_to = team_img_path,
                                   processors = [ResizeToFill(
                                       width=1280, height=480, upscale=True)],
                                   format='JPEG',
                                   options={'quality':90},
                                   blank=True,
                                   null=True)
    team_detail = RichTextUploadingField(config_name='default', blank=True, null=True)

    def __str__(self):
        return '%s' % self.name

    def delete(self, *args, **kwargs):
        if self.logo or self.team_banner:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.logo.path))
            os.remove(os.path.join(settings.MEDIA_ROOT, self.team_banner.path))
        super(Team, self).delete(*args, **kwargs)


class TeamOrg(MPTTModel):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, related_name='team_org')
    parent = TreeForeignKey('self', verbose_name='parent', related_name='children', on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
    position = models.CharField(verbose_name='직책', max_length=30, default="팀장")
    authority = models.BooleanField(default=False)

    class Meta:
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['parent']

    @property
    def title(self):
        return self.team.name
    @property
    def is_leader(self):
        if self.level == 0:
            return True
        else:
            return False
CAREER_LEVEL = [
    ('1','경력 무관'),
    ('2','2년 미만'),
    ('3','5년 미만'),
    ('4','10년 미만'),
    ('5','10년 이상'),
]

class FindMember(BaseModel):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='find_member')
    title = models.CharField(max_length=200)
    essencial = models.CharField(max_length=200)
    plus = models.CharField(max_length=100)
    msg = RichTextUploadingField(config_name='default', blank=True, null=True)
    manpower = models.IntegerField()
    career = models.CharField(max_length=1, choices=CAREER_LEVEL)
    contact_name = models.CharField(max_length=100)
    contact_phone = models.CharField(max_length=100)
    contact_email = models.EmailField(max_length=254)

    def __str__(self):
        return f"{self.title} of {self.team.name}"


REG_STATUS = [
    ('1', 'REGISTERED'),
    ('2', 'APPROVE'),
    ('3', 'REJECT'),
]


class RegisteredMember(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    notice = models.ForeignKey(FindMember, on_delete=models.CASCADE, related_name='registered_user', null=True, blank=True)
    status = models.CharField(max_length=1, choices=REG_STATUS, null=True)
    msg = RichTextUploadingField(config_name='default', blank=True, null=True)

    def __str__(self):
        return f"{self.user} request for {self.team.name}"

apps/teams/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from ckeditor.widgets import CKEditorWidget

CHOICES = [
    ('1', '창업'),
    ('2', '취미'),
    ('3', '사이드프로젝트'),
    ('4', '스터디'),
    ('5', 'ETC'),
]

class TeamRegisterForm(forms.ModelForm):
    name = forms.CharField(label='팀 이름', widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '팀 이름을 알려주세요 (최대 20자)'
    }))
    short_description = forms.CharField(label='팀 소개', widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '간략한 팀 소개를 작성해주세요 (최대 50자)'
    }))
    purpose = forms.CharField(widget=forms.Select(choices=CHOICES, attrs={
        'required':'required'
    }))
    logo = forms.FileField(label='팀 로고', widget=forms.FileInput(attrs={
        'class':'hidden',
        'required':'required'
    }))
    team_banner = forms.FileField(label='팀 배너', widget=forms.FileInput(attrs={
        'class':'hidden',
        'required':'required'
    }))
    class Meta:
        model = Team
        field = '__all__'
        exclude = ()


CAREERS = [
    ('1','경력 무관'),
    ('2','2년 미만'),
    ('3','5년 미만'),
    ('4','10년 미만'),
    ('5','10년 이상'),
]


class TeamRecruitForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집공고 제목을 입력해주세요.'
    }))
    essencial = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '지원자격을 입력해주세요.'
    }))
    plus = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '우대사항을 입력해주세요.'
    }))
    manpower = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 인원 수를 입력해주세요.'
    }))
    career = forms.CharField(widget=forms.Select(choices=CAREERS, attrs={
        'required':'required'
    }))
    contact_name = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 담당자 이름을 입력해주세요.'
    }))
    contact_phone = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 담당자 전화번호를 입력해주세요.'
    }))
    contact_email = forms.CharField(widget=forms.TextInput(attrs={
        'class':'team_input',
        'placeholder': '모집 담당자 이메일주소를 입력해주세요.'
    }))
    msg = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = FindMember
        field = '__all__'
        exclude = ('team',)


class RegisterRequestForm(forms.ModelForm):

    class Meta:
        model = RegisteredMember
        field = '__all__'
        exclude = ('user','team','status',)

apps/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from apps.teams.models import *
from apps.member.models import *
from apps.teams.forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from ckeditor.fields import RichTextField
from django.urls import reverse
# Create your views here.

def main_page(request):
    teams = Team.objects.all()
    context = {
        'teams':teams,
    }
    return render(request, 'findteam/teams.html', context)


def member_list(request):
    members = Profile.objects.all()
    context = {
        'members':members,
    }
    return render(request, 'findmate/members.html', context)


@login_required
def make_team(request):
    posting_type = "create"
    if request.method == 'POST':
        form = TeamRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            newTeam = form.save(commit=False)
            newTeam.save()
            print(newTeam)
            team_org = TeamOrg.objects.create(user=request.user, team=newTeam)
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = TeamRegisterForm()
    context = {
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findteam/maketeam.html', context)

@login_required
def update_team(request, team_pk):
    posting_type = "update"
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        print('업데이트 시작')
        form = TeamRegisterForm(request.POST, request.FILES, instance=team)
        print(form)
        if form.is_valid():
            print('The form is valid')
            newTeam = form.save(commit=False)
            newTeam.save()
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = TeamRegisterForm(instance=team)
    context = {
        'team':team,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findteam/maketeam.html', context)

@login_required
def team_select(request):
    teams = Team.objects.filter(team_org__user=request.user, team_org__level=0)
    context = {
        'teams':teams,
    }
    return render(request, 'findmate/select_team.html', context)

@login_required
def team_recruit(request, team_pk):
    posting_type = "create"
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        form = TeamRecruitForm(request.POST, request.FILES)
        if form.is_valid():
            newRecruit = form.save(commit=False)
            newRecruit.team = team
            newRecruit.save()
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = TeamRecruitForm()
    context = {
        'team':team,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findmate/recruit.html', context)

@login_required
def update_recruit(request, recruit_pk):
    posting_type = "update"
    recruit = get_object_or_404(FindMember, pk=recruit_pk)
    team = recruit.team
    if request.method == 'POST':
        form = TeamRecruitForm(request.POST, request.FILES, instance=recruit)
        if form.is_valid():
            newRecruit = form.save(commit=False)
            newRecruit.team = team
            newRecruit.save()
            form.save_m2m()

            return redirect(reverse('core:team_management', kwargs={"team_pk": team.pk}))
    else:
        form = TeamRecruitForm(instance=recruit)
    context = {
        'team':team,
        'recruit':recruit,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findmate/recruit.html', context)


# 팀 디테일 페이지
@login_required
def team_detail(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    team_org = TeamOrg.objects.filter(team=team)
    try:
        if team_org.get(Q(user=request.user)&(Q(position="팀장")|Q(position="부팀장"))):
            authority = True
    except:
        authority = False        
    context = {
        'team':team,
        'team_org':team_org,
        'authority':authority,
    }
    return render(request, 'findteam/team_detail.html', context)


# 팀 가입 신청 페이지
@login_required
def team_register_reqeust(request, team_pk):
    posting_type = "create"
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        form = RegisterRequestForm(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            newRequest = form.save(commit=False)
            newRequest.team = team
            newRequest.user = request.user
            newRequest.status = '1'
            newRequest.save()
            form.save_m2m()

            return redirect('core:main_page')
    else:
        form = RegisterRequestForm()
    context = {
        'team':team,
        'form':form,
        'posting_type':posting_type,
    }
    return render(request, 'findteam/team_register.html', context)


# 팀관리 페이지
@login_required
def team_management(request, team_pk):
    # 팀 관리페이지 첫 로딩에 필요한 팀 정보
    team = get_object_or_404(Team, pk=team_pk)

    # 팀 기본정보 관리에 필요한 코드
    team_base_form = TeamRegisterForm(instance=team)

    # 팀 조직도 정보
    team_org = TeamOrg.objects.filter(team=team)

    # 팀 모집공고용 ckeditor
    recruit_update_form = TeamRecruitForm()

    context = {
        'team':team,
        'team_base_form':team_base_form,
        'team_org':team_org,
        'recruit_update_form':recruit_update_form,
    }
    return render(request, 'findteam/team_management.html', context)


@login_required
def team_delete(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    team.delete()
    return redirect('/')

apps/teams/views.py
from django.shortcuts import render

# Create your views here.

apps/core/templates/findteam/maketeam.html
{% extends "index.html" %}

{% block title %}
팀 생성
{% endblock %}

{% block style %}
<style>
    .make_team_wrapper {
        padding: 2rem 1rem;
    }

    .box {
        border: 1px solid #efefef;
        background-color: #ffffff;
        box-shadow: 0px 0px 30px #eee;
        width: 1280px;
        margin: auto;
    }

    .form_header {
        border-bottom: 1px solid #efefef;
        padding: 1rem 2rem;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .form_header h3 {
        font-weight: 600;
        font-size: 1.2rem;
    }

    .form_header span {
        font-size: .8rem;
        color: gray;
    }

    .form_content {
        padding: 0 2rem;
    }

    .form_control {
        margin: 1rem 0;
    }

    .team_input {
        margin-left: 2rem;
        width: 480px;
        height: 48px;
        border: none;
        border-bottom: 1px solid #efefef;
        padding: .5rem;
        font-size: 1rem;
        font-weight: 300;
        outline: none;
    }

    .form_label {
        font-size: 1rem;
        font-weight: 300;
    }

    .django-ckeditor-widget {
        width: 100%;
        margin-top: 1rem;
    }

    .btn {
        cursor: pointer;
        padding: .5rem 2rem;
        color: #ffffff;
        font-size: 1rem;
        font-weight: 300;
        background-color: gray;
    }

    .register_team {
        background-color: #0099cc;
        border: none;
    }

    .form_control select {
        margin-left: 2rem;
        width: 480px;
        height: 48px;
        border: none;
        border-bottom: 1px solid #efefef;
        padding: .5rem;
        font-size: 1rem;
        font-weight: 300;
        outline: none;
    }

    .form_control input[type='file'] {
        visibility: hidden;
    }

    .upload_label {
        background-color: #0099ee;
        padding: .3rem 1.2rem;
        font-size: .8rem;
        border-radius: 4px;
        color: white;
        margin-left: 2rem;
    }

    .form_control #text {
        display: none;
    }
</style>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block content %}

<div class="make_team_wrapper">
    <div class="form_wrapper box">
        <form method="POST"
            action="{% if posting_type == 'create' %}{% url 'core:make_team' %}{% else  %}{% url 'core:update_team' team.pk %}{% endif %}"
            enctype="multipart/form-data">
            <div class="form_header">
                <div class="header_text">
                    <h3>새로운 팀 만들기</h3>
                    <span>아래 정보를 기입하여 새로운 팀을 생성합니다.</span>
                </div>
                <div class="btn_list">
                    <a class="btn back_to_list">돌아가기</a>
                    <input type="submit" class="btn register_team" value="등록하기">
                </div>
            </div>
            <div class="form_content">
                {% csrf_token %}
                <div class="form_control">
                    <label class="form_label" for="team_name">팀 이름</label>
                    {{form.name}}
                </div>
                <div class="form_control">
                    <label class="form_label" for="team_desc">팀 소개</label>
                    {{form.short_description}}
                </div>
                <div class="form_control">
                    <label class="form_label" for="id_purpose">팀 목표</label>
                    {{form.purpose}}
                </div>
                <div class="form_control">
                    <span class="form_label">팀 로고</span>
                    <label class="upload_label" for="id_logo">업로드 (200x200)</label>
                    {{form.logo}}
                </div>
                <div class="form_control">
                    <span class="form_label">팀 배너</span>
                    <label class="upload_label" for="id_team_banner">업로드 (1280x480)</label>
                    {{form.team_banner}}
                </div>
                <div class="form_control">
                    <h4 class="form_label" class="form_label">팀 소개</h4>
                    {{form.media}}
                    {{form.team_detail|safe}}
                </div>

            </div>
        </form>
    </div>

</div>

<script>
    let url = ""
</script>
{% endblock %}

apps/core/templates/findteam/team_detail.html
{% extends "index.html" %}

{% block title %}
{{team.name}}
{% endblock %}

{% block style %}
<style>
    .main_contents {
        background-color: #ffffff;
    }

    .team_wrapper {
        padding: 0rem 2rem;
        width: 1280px;
        margin: auto;
    }

    .team_wrapper>img {
        width: 100%;
    }

    .team_name span {
        font-size: .9rem;
        color: gray;
        font-weight: 300;
    }

    .team_header {
        padding: 1rem 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .team_mgmt {
        background-color: #0C7BB3;
        color: white;
        padding: .5rem 2rem;
        border-radius: 4px;
    }

    .name_desc span {
        font-weight: 300;
    }

    .member_and_notice {
        padding: 1rem 0;
        border-top: 1px solid gray;
        border-bottom: 1px solid gray;
        display: flex;
    }

    .team_members {
        padding-right: 2rem;
        border-right: 1px solid #efefef;
        min-width: 450px;
    }

    .team_members h4 {
        font-weight: 500;
        display: block;
    }

    .member_list {
        margin-top: 1rem;
        display: flex;
        align-items: center;
    }

    .member_item {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-right: 1rem;
        font-size: .8rem;
        font-weight: 300;
    }

    .member_item img {
        width: 48px;
        height: 48px;
        border-radius: 50%;
    }

    .find_members {
        padding-left: 2rem;
    }

    .team_detail {
        margin: 2rem 0;
    }

    .check_notice {
        margin-top: 1rem;
        background-color: #2b2b2b;
        color: white;
        font-size: .9rem;
        font-weight: 500;
        text-align: center;
        padding: .8rem;
        border-radius: 4px;
        cursor: pointer;
    }

    .check_notice:hover {
        background-color: pink;
        color: #2b2b2b;
    }
</style>

{% endblock %}

{% block header_content %}

{% endblock %}

{% block content %}

<div class="team_wrapper">
    <img src="{{team.team_banner.url}}">
    <div class="team_header">
        <div class="name_desc">
            <h2 class="team_name">{{team.name}} <span>({{team.get_purpose_display}})</span></h2>
            <span>{{team.short_description}}</span>
        </div>
        {% if authority %}
        <a href="{% url 'core:team_management' team.pk %}" class="btn team_mgmt">팀 관리</a>
        {%endif%}
    </div>
    <div class="member_and_notice">
        <div class="team_members">
            <h4>현재 팀원 ({{team_org.count}}명)</h4>
            <div class="member_list">
                {% load mptt_tags %}
                {% recursetree team_org %}
                <a href="{% url 'member:member_info' node.user.pk %}" class="member_item">
                    <img src="{{node.user.profile.picture.url}}">
                    <span>{{node.user.profile.name}}</span>
                    <span>({{node.position}})</span>
                </a>
                {% if not node.is_leaf_node %}
                {{children}}
                {% endif %}
                {% endrecursetree %}
            </div>
        </div>
        <div class="find_members">
            <h4>모집 공고</h4>
            <span>모집중인 공고가 {{team.find_member.all.count}}개 있습니다.</span>
            <h4 class="check_notice career_info" data-team="{{team.id}}">모집공고 확인하기</h4>
        </div>
    </div>

    <div class="team_detail">
        {{team.team_detail|safe}}
    </div>

</div>

<div class="popup_wrapper hidden">
    <div class="popup_bg"></div>
    <div class="popup_window">
        <div class="career_header">
            <div>
                <h4>FindMate팀의 모집공고</h4>
                <span>아직 모집중인 공고가 없습니다.</span>
            </div>
            <span class="close_btn"><i class="far fa-times-circle"></i>닫기</span>
        </div>
        <div class="career_tab">
            <div class="tab_left">
                <ul>
                    <li>
                        <h5></h5><span></span>
                    </li>
                </ul>
            </div>
            <div class="tab_content">

            </div>
        </div>
    </div>
</div>


<!-- 모집공고 팝업 -->
<script type="text/javascript" src="/static/js/team_notice.js"></script>


{% endblock %}

apps/core/templates/findteam/teams.html
{% extends "index.html" %}
{% load static %}
{% block title %}
팀 찾기
{% endblock %}

{% block style %}
<style>
    .team_box_wrapper {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        width: 1280px;
        ;
        margin: auto;
    }

    .team_box {
        margin: 1rem auto 0;
        border: 1px solid #efefef;
        max-width: 400px;
        background-color: white;
        box-shadow: 0px 0px 30px #eee;
    }

    .team_img {
        margin: auto;
        display: block;
        width: 100%;
        height: auto;
    }

    .team_info {
        padding: 1rem;
        display: flex;
        align-items: center;
    }

    .team_info h4 {
        font-size: 1.2em;
        font-weight: 400;
        max-width: 280px;
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
    }

    .team_info span {
        font-size: .9rem;
        font-weight: 300;
    }

    .team_info .team_logo {
        width: 80px;
        height: 80px;
        border: 1px solid #efefef;
        border-radius: 50%;
        margin-right: 1rem;
    }

    .career_info {
        border-top: 1px solid #efefef;
        padding: 1rem;
        font-size: .9rem;
        font-weight: 300;
        z-index: 8;
    }

    .team_name {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .team_desc {
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
    }

    span.team_category {
        font-size: .8rem;
        color: gray;
    }

    /* 팝업 관련 */
    body {
        position: relative;
    }

    .popup_wrapper {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
    }

    .popup_bg {
        width: 100%;
        height: 100%;
        background-color: black;
        opacity: .5;
        position: relative;
    }

    .popup_window {
        position: absolute;
        width: 1080px;
        height: 580px;
        /* top: calc(50vh - 290px);
        left: calc(50vw - 540px); */
        background-color: white;
        padding: 2rem 1.5rem;
        overflow: scroll;
    }

    .career_header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid #EFEFEF;
        padding-bottom: 1rem;
    }

    .close_btn {
        color: gray;
        font-size: .9rem;
        cursor: pointer;
    }

    .close_btn i {
        color: gray;
        margin-right: .5rem;
    }

    .career_tab {
        display: flex;
    }

    .tab_left {
        width: 30%;
        max-height: 460px;
        overflow: scroll;
    }

    .tab_left ul li {
        padding: 1rem .5rem;
        border-bottom: 1px solid #EFEFEF;
    }

    .tab_left ul li:hover {
        background-color: #fafafa;
    }

    .tab_left ul li h5 {
        font-weight: 500;
    }

    .tab_left ul li span {
        font-size: .8rem;
        color: gray;
        font-weight: 300;
    }

    .tab_content {
        width: 70%;
        padding: 1rem;
        max-height: 460px;
        overflow: scroll;
    }

    .tab_content img {
        max-width: 100%;
    }

    .hidden {
        display: none;
    }
</style>
{% endblock %}

{% block header_content %}

<div class="filter">
    <div class="filter_item_list">
        <span>지역</span>
        <span>직무</span>
        <span>경력</span>
        <span>목적</span>
    </div>
    <div class="create_post">
        <a href="{% url 'core:make_team' %}">새로운 팀 만들기</a>
    </div>

</div>

{% endblock %}

{% block content %}

<div class="team_box_wrapper">

    {% for team in teams %}
    <div class="team_box">
        {% if team.team_banner %}
        <a href="{% url 'core:team_detail' team.pk %}"><img class="team_img" src="{{team.team_banner.url}}"></a>
        {% else %}
        <a href="{% url 'core:team_detail' team.pk %}"><img class="team_img" src="https://picsum.photos/1280/480"></a>
        {% endif %}
        <a href="{% url 'core:team_detail' team.pk %}" class="team_info">
            {% if team.logo %}
            <img class="team_logo" src="{{team.logo.url}}">
            {% else %}
            <img class="team_logo" src="https://picsum.photos/200/200">
            {% endif %}
            <div>
                <div class="team_name">
                    <h4>{{team.name}}</h4>
                    <span class="team_category">{{team.get_purpose_display}}</span>
                </div>
                <span class='team_desc'>{{team.short_description}}</span>
            </div>

        </a>
        {% if team.find_member %}
        <div class="career_info" data-team="{{team.pk}}">
            <span>함께할 {{team.find_member.all|length}}개의 포지션을 찾고있어요</span>
        </div>
        {% endif %}
    </div>
    {% endfor %}

</div>
<div class="popup_wrapper hidden">
    <div class="popup_bg"></div>
    <div class="popup_window">
        <div class="career_header">
            <div>
                <h4>FindMate팀의 모집공고</h4>
                <span>모집공고가 3개 있습니다.</span>
            </div>
            <span class="close_btn"><i class="far fa-times-circle"></i>닫기</span>
        </div>
        <div class="career_tab">
            <div class="tab_left">
                <ul>
                    <li>
                        <h5>디자이너 구합니다.</h5><span>5명 / 10년 이상</span>
                    </li>
                    <li>
                        <h5>참신한 기획자를 찾아요!</h5><span>5명 / 10년 이상</span>
                    </li>
                    <li>
                        <h5>저희를 구원해줄 투자자 어디없나요</h5><span>5명 / 10년 이상</span>
                    </li>
                </ul>
            </div>
            <div class="tab_content">
                this is content
            </div>
        </div>

    </div>

</div>

<!-- 모집공고 팝업 -->
<script type="text/javascript" src="/static/js/team_notice.js"></script>
{% endblock %}